on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azccr1.azurecr.io
        username: ${{ secrets.acr_azccr1_username }}
        password: ${{ secrets.acr_azccr1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/hello" -f  "anil" -t azccr1.azurecr.io/anilak1:${{ github.sha }} --label dockerfile-path=anil
        docker push azccr1.azurecr.io/anilak1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_anilak1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: azccr1.azurecr.io
        container-registry-username: ${{ secrets.acr_azccr1_username }}
        container-registry-password: ${{ secrets.acr_azccr1_password }}
        secret-name: anilak1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azccr1.azurecr.io/anilak1:${{ github.sha }}
        imagepullsecrets: |
          anilak1dockerauth
